name: Deploy Results Viewer to Github Pages

on:
  push:
    branches: [ "main" ]

env:
  Configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
      
    - name: Publish project
      run: dotnet publish ./ResultsWebViewer/ResultsWebViewer.csproj -o release -p:GHPages=true --nologo

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
