name: Run Benchmark

on: workflow_dispatch

env:
  Configuration: Release
  
permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build
      
    - name: Run Benchmark
      run: dotnet run --project ./Runner/Runner.csproj --filter "Runner.Benchmarks.LoadGrainBenchmark+EventStorageBasedProviders.LoadGrainFromStorage*Memory*" --job Dry --artifacts artifacts
      
    - name: Get current date and time
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD-HH.mm.ss"
        
    - name: Get body text
      id: body
      run: echo "BODY_TEXT=$(cat $(ls *.md))" >> "$GITHUB_OUTPUT"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.body.outputs.BODY_TEXT }}
        tag_name: ${{ steps.date.outputs.time }}
        files: artifacts/**/*