name: Run Benchmark

on: workflow_dispatch

env:
  Configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build
      
    - name: Run Benchmark
      run: dotnet run --project ./Runner/Runner.csproj --filter '*' 
      
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ./Runner/bin/**/BenchmarkDotNet.Artifacts/results/*